name: Continuous Integration
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/.github/**'
  pull_request:
    branches:
      - master

jobs:
  package:
    name: Package
    uses: ./.github/workflows/package.yml
    with:
      build_linux: true
      build_windows: true
