name: Package All and Create Release
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: Tag Name (new or existing)
        required: true
        type: string
      prerelease:
        description: Pre-release?
        default: true
        type: boolean

jobs:
  linux:
    name: Package Linux
    uses: ./.github/workflows/package-linux.yml

  windows:
    name: Package Windows
    uses: ./.github/workflows/package-windows.yml

  macos:
    name: Package MacOS
    uses: ./.github/workflows/package-macos.yml

  release:
    name: Create Release
    runs-on: ubuntu-22.04
    needs:
      - linux
      - windows
      - macos
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4

      - name: Display Artifacts
        run: ls -R

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.tag_name }}
          prerelease: ${{ inputs.prerelease }}
          files: |
            linux-appimage/*.zip
            windows/*.zip
            macos/*.zip
