name: Package All and Create Release
on:
  workflow_dispatch:
    inputs:
      build_linux:
        description: Build Linux?
        default: true
        type: boolean
      build_windows:
        description: Build Windows?
        default: true
        type: boolean
      build_macos:
        description: Build MacOS?
        default: true
        type: boolean
      tag_name:
        description: Tag Name (new or existing)
        required: true
        type: string
      prerelease:
        description: Pre-release?
        default: true
        type: boolean

jobs:
  package:
    name: Package
    uses: ./.github/workflows/package.yml
    with:
      build_linux: ${{ inputs.build_linux }}
      build_windows: ${{ inputs.build_windows }}
      build_macos: ${{ inputs.build_macos }}

  release:
    name: Create Release
    runs-on: ubuntu-22.04
    needs:
      - linux
      - windows
      - macos
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4

      - name: Display Artifacts
        run: ls -R

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.tag_name }}
          prerelease: ${{ inputs.prerelease }}
          files: |
            linux-appimage/*.zip
            windows/*.zip
            macos/*.zip
